% returns the trained model

function net = train_model(imdsTrain, imdsValidation, lgraph)
    options = trainingOptions('sgdm', ...
        'MiniBatchSize', 32, ...
        'MaxEpochs', 10, ...
        'InitialLearnRate', 1e-4, ...
        'ValidationData', imdsValidation, ...
        'ValidationFrequency', 30, ...
        'Verbose', true, ...
        'Plots', 'training-progress');

    net = trainNetwork(imdsTrain, lgraph, options);
end
